# Generated by Django 6.0.5 on 2026-06-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre / Razón Social')),
                ('cuit', models.CharField(max_length=50, verbose_name='CUIT')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('tipo_destino', models.CharField(default='Único', max_length=50)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_carga', models.CharField(max_length=100)),
                ('peso_estimado', models.CharField(blank=True, max_length=100, null=True)),
                ('mercaderia', models.TextField(verbose_name='Descripción de Mercadería')),
                ('quiere_seguro', models.BooleanField(default=False)),
                ('suma_asegurada', models.CharField(blank=True, max_length=100, null=True)),
                ('cobertura_basica', models.CharField(blank=True, max_length=100, null=True)),
                ('archivo_poliza', models.FileField(blank=True, null=True, upload_to='polizas/')),
                ('aseguradora', models.CharField(blank=True, max_length=100, null=True)),
                ('adicionales', models.TextField(blank=True, help_text='Coberturas adicionales detectadas', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
